* Scramble

  This is a learning project for creating a http api using clojure, which
  consists in a backend server responding HTTP requests at ~/scramble~ route,
  made with clojure, and a frontend javascript handling a simple form that sends
  an AJAX request to the backend.

** Dependencies

   Packages:
   - Clojure
   - leiningen

   Clojure Modules:
   - compojure
   - http-kit
   - org.clojure/clojure
   - org.clojure/clojurescript
   - reagent
   - re-frame
   - day8.re-frame/http-fx

** The Backend

   The [[scramble/][scramble]] directory reflects the backend source code. Once started, the
   server handles only the route ~scramble/~, denying all the others which does
   not match.

   For more details about the backend, please see its [[scramble/README.org][README]].

*** Running the API server

    To run the API server, just asks leiningen to do so:
    #+BEGIN_SRC sh
    $ cd scramble
    $ lein run
    #+END_SRC

** The Frontend

   The [[scramble-ui/][scramble-ui]] directory reflects the frontend source code. It's a
   ClojureScript project, which needs to be compiled to ~.js~.

*** Compiling the scramble-ui

    #+BEGIN_SRC sh
    $ lein cljsbuild once dev
    #+END_SRC

*** Running the frontend

    There is no server to run the frontend, so you need to open the /index.html/
    locally after the build is done.

    Notice that the host and port of the API server is defined by the javascript
    and right now is defined to ~http://ice.vms:3000~. You may change it or add
